### ISSUE TITLE
Changes made to the Facebook Login SDK for iOS

### ISSUE THREAD

**Issue by ciccilleju** [capacitor-community/facebook-login#151]
I can't login to facebook iOS anymore and i read about this:
https://developers.facebook.com/blog/post/2024/03/28/changes-made-to-fb-login-sdk/

does anybody know what should I do to make it work again?

thanks

**Comment by ciccilleju** [comment]
@rdlabo Android works fine as you can see from this screenshot

but iOS asks me about a "limite" api which i never heard about.

<img width="628" alt="image" src="https://github.com/capacitor-community/facebook-login/assets/42606234/6c220cd5-209a-4b35-99c9-33239c61f63e">

Rolling back to 5.0.3 fixes the iOS issue.
I don't know if you were aware of it

**Comment by wickker** [comment]
Hihi, had the same issue but once I accepted Apple's ATT permission it defaulted back to the normal login flow instead of limited. Maybe you can try https://github.com/mahnuh/capacitor-plugin-app-tracking-transparency to enable the prompt which worked for me.

**Comment by ciccilleju** [comment]
> I have the same problem. How did you solve it? @ciccilleju

disabling facebook login at the moment

**Comment by ciccilleju** [comment]
> Hihi, had the same issue but once I accepted Apple's ATT permission it defaulted back to the normal login flow instead of limited. Maybe you can try https://github.com/mahnuh/capacitor-plugin-app-tracking-transparency to enable the prompt which worked for me.

let me try it and I'll get back to you

**Comment by dragermrb** [comment]
What happens if the user does not accept tracking?

**Comment by ciccilleju** [comment]
you must use the facebook limited login, which works differently

**Comment by dragermrb** [comment]
Can this plugin do limited login?

I never got an answer when I asked https://github.com/capacitor-community/facebook-login/issues/93

**Comment by ciccilleju** [comment]
no but this may help you
https://github.com/capacitor-community/facebook-login/pull/150

**Comment by dragermrb** [comment]
Thank you!

I'm the author of the original PR (https://github.com/capacitor-community/facebook-login/pull/94) and I've had a fork for a while (https://github.com/dragermrb/capacitor-plugin-facebook-login), but I wanted to see if I could get back to the community plugin.

**Comment by shiv19** [comment]
@dragermrb you can reach out to @mhartington if you want to maintain this community plugin.

**Comment by SimpleHacker409** [comment]
@wickker it didn't work for me, I am asking for the tracking permission before Facebook login, and even after allowing 
it is still the same error.

**Comment by viking2917** [comment]
@dragermrb thank you for the fork! Have you tried or been able to combine your fork and limited login with Firebase auth? The limited login seems to return a JWT token, which I don't think one can pass for Firebase's signInWithCredential method...

**Comment by dragermrb** [comment]
Hello, I currently do not use firebase, I validate the token in my own backend and authenticate the user if correct

**Comment by theigl** [comment]
@rdlabo any chance we can get any of the proposed solutions for limited login applied to this repo?

**Comment by forgr-owner** [comment]
You can now use https://github.com/Cap-go/capacitor-social-login who implement Facebook with the latest SDK and limited login, and it's maintain by a company who maintain more than 30 plugins.

**Comment by abennouna** [comment]
Seems solved by version 6.1.0

**Comment by ciccilleju** [comment]
I’ve installed the latest version (6.1.0). Is it normal to receive a different type of token depending on the operating system?

I thought this behavior was resolved when using the "limited" option.

Regardless, I tried both tracking: 'enabled' and tracking: 'limited', but the accessToken doesn’t change (tracking is enabled). On iOS, I receive a JWT token, while on Android, I get an OAuth2 token.

Thank you!

**Comment by ciccilleju** [comment]
@dragermrb i've added the tracking but i still getting JWT

what am i doing wrong here?
`
  async fbLogin() {
    const FACEBOOK_PERMISSIONS = ['public_profile', 'email'];

    const fbLoginProcessIOS = async () => {
      const response = await this.trackingService.getStatus();
      if (response.status === 'authorized') {
        await this.fbLoginIOS(FACEBOOK_PERMISSIONS);
      } else {
        const requestResponse = await this.trackingService.requestPermission();
        if (requestResponse.status === 'authorized') {
          await this.fbLoginIOS(FACEBOOK_PERMISSIONS);
        } else {
          alert('Devi consentire i tracciamenti per poter utilizzare questa funzione');
        }
      }
    };

    if (this.spiaggiaService.isPlatformAndroid) {
      await this.fbLoginAndroid(FACEBOOK_PERMISSIONS);
    } else if (this.spiaggiaService.isPlatformIos) {
      await fbLoginProcessIOS();
    }
  }

  async fbLoginIOS(FACEBOOK_PERMISSIONS: string[]) {
    const result = await (<LimitedFacebookLoginResponse><unknown>(
      FacebookLogin.login({ permissions: FACEBOOK_PERMISSIONS, tracking: 'enabled' })
    ));
 
    console.log({ result });

    // this.loginFacebook(this.myService.serviziRest.loginFbIos, result.accessToken.token, result.accessToken.userId, result.accessToken.email);
  }`

**Comment by dragermrb** [comment]
Hi @ciccilleju 

Sorry for the mistake, but some changes have been implemented with respect to the PR I made some time ago and my previous answer is not correct.

Maybe someone has the same problem and can help you...

**Comment by ciccilleju** [comment]
thanks @dragermrb 

I've tried all possible combinations and checked all the options on my facebook developer page, but iOS always returns a JWT, while Android returns an OAuth2 token (no matter if i change the "tracking" option from limited to enabled or if i remove it completely)

If this is the expected and final behavior, I'll update my backend since I don't see many other options.

However, if you have any suggestions, I'd love to hear them!

**Comment by ciccilleju** [comment]
@rdlabo any chance to get a oauth2 access token with ios login, as already happens with android login?

thanks!

**Comment by anitamatyas** [comment]
@ciccilleju same thing happens in my case. I always get a JWT token on IOS. It messes with the implementation of my 2fa flow, and causes lots of issues with Firebase auth. 
Did you find any solution for this problem?

**Comment by forgr-owner** [comment]
That a bit messy from Facebook, we documented it here: 
https://capgo.app/docs/plugins/social-login/facebook/#understanding-facebook-login-token-types
We also added in our plugin a method to ask app tracking, when you want to use the old OAuth token.
You can find it here: https://github.com/Cap-go/capacitor-social-login?tab=readme-ov-file#providerspecificcall-1

Thanks @viking2917, for explaining better what happened. We enhanced the doc

**Comment by viking2917** [comment]
@forgr-owner thanks for that, especially the details about server-side validation. My experience with this plugin differs from what is documented in the link you shared, I get a JWT token from this plugin whether I ask for app tracking to be allowed or denied. I am not sure that's the correct behavior, but it seems to be what's happening...

**Comment by viking2917** [comment]
@forgr-owner just to be clear your documentation is for a different plugin that this one, correct? 

I understand about the ATT; even if I accept app tracking through the permissions, I still get a JWT token. I think this may be related to some recent pull requests into this plugin, and this behavior may be specific to this plugin.
