### ISSUE TITLE
Login error on android

### ISSUE THREAD

**Issue by ghonche** [capacitor-community/facebook-login#83]
**Describe the bug**
When I tried to login with facebook, this error occurred:
 
> There is an error in logging you into this application please try again later.
(screenshot attached.)

**To Reproduce**
1. use @capacitor-community/facebook-login to implement Facebook authentication on your app.
2. Generate signed APK of the app.
3. install [Facebook application](https://play.google.com/store/apps/details?id=com.facebook.katana) on an android device 
3. Install your app and try to login using Facebook on the same device.

**Expected behavior**
Login must complete successfully.

**Screenshots**

![photo_2022-02-20_16-30-39](https://user-images.githubusercontent.com/25591295/154843986-3fee3a5f-fe5c-40d2-9e43-327e0cfce286.jpg)

**Smartphone:**
 - Device: Samsung A72
 - OS: Android 11

**Additional context**
Please consider that the bug happens when the [Facebook application](https://play.google.com/store/apps/details?id=com.facebook.katana) is installed. And it only exists on signed apk.
It is also reported in [react-native-facebook-login ](https://github.com/magus/react-native-facebook-login/issues/323).
Also note that i've already added key hash on facebook dashboard.

**Comment by rdlabo** [comment]
@ghonche This may be only debug mode. Please try this:
https://stackoverflow.com/questions/7506392/how-to-create-android-facebook-key-hash

**Comment by ghonche** [comment]
> @ghonche This may be only debug mode. Please try this: https://stackoverflow.com/questions/70506466/invalid-key-hash-facebook-login

No, I don't think it's related to key hash. 
I got my release certificate fingerprint using this command:
`keytool -list -v \
-alias <your-key-name> -keystore <path-to-production-keystore>` from [this doc](https://developers.google.com/android/guides/client-auth) 
And then generated key hash using this command:
`echo <SHA1 fingerprint> | xxd -r -p | openssl base64`
or [this link](http://tomeko.net/online_tools/hex_to_base64.php).
Then I copied and pasted this Release Key Hash into Facebook Android settings.

**Comment by rdlabo** [comment]
Did you try to using singed apk?? Even if the key is correct, it will be useless if the apk file is not signed.

**Comment by ghonche** [comment]
Yeah I did sign the APK. I generated the APK using Android Studio ----> Build menu ---> Generate Signed Bundle/APK...
I believe the problem is not related to the wrapper plugin because as far as i know, same issue exists in ionic and react native Facebook plugins (issues [here](https://github.com/magus/react-native-facebook-login/issues/323) and [here](https://github.com/cordova-plugin-facebook-connect/cordova-plugin-facebook-connect/issues/108)).
By the way, I fixed this issue for myself by forcing facebook to login through web dialog. This stops the native Facebook app from interfering. It works for me. 
Take a look if you want: https://github.com/capacitor-community/facebook-login/pull/84

**Comment by rdlabo** [comment]
The difficulty with this problem is that the application I am releasing works fine on the actual device of android:
https://play.google.com/store/apps/details?id=jp.rdlabo.tipsys

@ghonche Can I try Facebook login with this app? First, isolate whether the problem is with the plug-in or with the actual device.

**Comment by ghonche** [comment]
Hi again.

**Comment by ghonche** [comment]
Hi again.
I tried Facebook login in your app. It worked fine. Of course it openes a web intent for facebook login. That's how I solved the bug for myself ([pull request](https://github.com/capacitor-community/facebook-login/pull/84#issuecomment-1092122850) ). The problem accures when you have Facebook app installed and a native intent opens.

**Comment by rdlabo** [comment]
Hi, again, and sorry for late.

I found https://github.com/magus/react-native-facebook-login/issues/297#issuecomment-433816732 , and sign key is changed at bundle.

If use "Build bundle", check SHA-1 on Google Play Console.

Thanks.

**Comment by Hansel03** [comment]
any solution for this error?

**Comment by co-dax** [comment]
I have fixed this by clearing mobile app cache and data.

**Comment by rdlabo** [comment]
Apologies that this old issue remained open.

The discussion identified this as a Facebook native-app session or application-signing configuration problem rather than a defect in this Capacitor wrapper. The same behavior was reported with other Facebook integrations, and the latest follow-up confirms that clearing the Facebook app’s cache and data resolved it.

The current plugin has also been verified successfully on a physical Android device with a signed build. I’m closing this as an external configuration/state issue. If the latest release reproduces a plugin-specific failure, please open a new issue with the native Facebook SDK error, signing configuration details, and a minimal reproduction.
